Program = {OpWhite Expr OpWhite.}.
Expr = | AssignExpr. | IfExpr. | InvkExpr. | DefExpr. ValExpr.....
BoolExpr = Expr OpWhite '==' OpWhite Expr.
SetExpr = '!Set' White Expr White Expr OpWhite '!'.
IfExpr = 'if' White Expr White 'then' White Expr White 'else' White Expr.
Args = {Arg White.}.
InvkExpr = FuncName '(' OpWhite Args OpWhite ')'.
Arg = Expr.
FuncName = VarName.
VarName = ~(Reserved.). {Char.}.
Reserved = | 'if'. | 'then'. 'else'...
Char = | Digit. Alpha..
DefExpr = '!DEF' White VarName OpWhite ':' OpWhite {BodyPair.} OpWhite '!'.
BodyPair = PartInvkExpr OpWhite PartInvkExpr .
PartInvkExpr = FuncName OpWhite '(' OpWhite '"' String '"'OpWhite ')'.
ValExpr = | '"' String '"'. VarName [{Accessor.}.]..
Accessor = '.' | 'name'. Num..
AssignExpr = VarName OpWhite '=' OpWhite Expr.
Num = {Digit.}.
String = {-'$'.'~'..}.
Digit = -'0'.'9'..
Alpha = |-'a'.'z'.. -'A'.'Z'...
White = {WhiteSpace.}.
OpWhite = [White.].
