Program = {Expr.}.
Expr = | InvkExpr. | ValExpr. | AssignExpr. DefExpr....
Args = {Arg.}.
InvkExpr = FuncName '(' Args ')'.
Arg = ValExpr.
LowerCase = |'a'.|'b'.|'c'.|'d'.|'e'.|'f'.|'g'.|'h'.|'i'.|'j'.|'k'.|'l'.|'m'.|'n'.|'o'.|'p'.|'q'.|'r'.|'s'.|'t'.|'u'.|'v'.|'w'.|'x'.|'y'. 'z'..........................
Char = | LowerCase. UpperCase..
VarName = {Char.}.
UpperCase = |'A'.|'B'.|'C'.|'D'.|'E'.|'F'.|'G'.|'H'.|'I'.|'J'.|'K'.|'L'.|'M'.|'N'.|'O'.|'P'.|'Q'.|'R'.|'S'.|'T'.|'U'.|'V'.|'W'.|'X'.|'Y'. 'Z'..........................
FuncName = VarName.
DefExpr = 'DEF' {BodyPair.}.
BodyPair = '"' VarName '"' VarName '"'.
ValExpr = | '"' VarName '"'. VarName ['.' VarName.]..
AssignExpr = VarName '=' Expr.

