Program = {Expr.}.
Expr = | AssignExpr. | InvkExpr. | DefExpr. ValExpr....
Args = {Arg.}.
InvkExpr = FuncName '(' Args ')'.
Arg = Expr.
FuncName = VarName.
VarName = {Char.}.
Char = | Digit. Alpha..
DefExpr = '!DEF' VarName ':' {BodyPair.}'!'.
BodyPair = InvkExpr InvkExpr .
ValExpr = | '"' String '"'. VarName ['.' VarName.]..
AssignExpr = VarName '=' Expr.
Num = {Digit.}.
String = {-'$'.'~'..}.
Digit = -'0'.'9'..
Alpha = |-'a'.'z'.. -'A'.'Z'...

